/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.27
 * Generated at: 2025-04-23 17:34:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.List;
import com.tms.beans.TrainBean;

public final class Fare_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.tms.beans.TrainBean");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>Fare Enquiry — E-Trains</title>\r\n");
      out.write("    <!-- Bootstrap CSS -->\r\n");
      out.write("    <link\r\n");
      out.write("      href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\"\r\n");
      out.write("      rel=\"stylesheet\"\r\n");
      out.write("      integrity=\"sha384-…\"\r\n");
      out.write("      crossorigin=\"anonymous\">\r\n");
      out.write("  </head>\r\n");
      out.write("  <body class=\"bg-light\">\r\n");
      out.write("\r\n");
      out.write("    <!-- NAVBAR -->\r\n");
      out.write("    <nav class=\"navbar navbar-expand-lg navbar-dark bg-primary\">\r\n");
      out.write("      <div class=\"container-fluid\">\r\n");
      out.write("        <a class=\"navbar-brand\" href=\"#\">National Ticket Booking Spot</a>\r\n");
      out.write("        <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\"\r\n");
      out.write("                data-bs-target=\"#navbarNav\" aria-controls=\"navbarNav\"\r\n");
      out.write("                aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("          <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("        </button>\r\n");
      out.write("    \r\n");
      out.write("        <div class=\"collapse navbar-collapse justify-content-end\" id=\"navbarNav\">\r\n");
      out.write("          <ul class=\"navbar-nav\">\r\n");
      out.write("            <li class=\"nav-item\"><a class=\"nav-link\" href=\"userhome\">Home</a></li>\r\n");
      out.write("            <li class=\"nav-item\"><a class=\"nav-link\" href=\"userviewtrainfwd\">View Trains</a></li>\r\n");
      out.write("            <li class=\"nav-item\"><a class=\"nav-link\" href=\"trainbwstnfwd\">Between Stations</a></li>\r\n");
      out.write("            <li class=\"nav-item\"><a class=\"nav-link\" href=\"bookingdetails\">History</a></li>\r\n");
      out.write("            <li class=\"nav-item\"><a class=\"nav-link active\" href=\"fareenqfwd\">Fare Enquiry</a></li>\r\n");
      out.write("            <li class=\"nav-item\"><a class=\"nav-link\" href=\"useravailfwd\">Seat Availability</a></li>\r\n");
      out.write("            <li class=\"nav-item\"><a class=\"nav-link\" href=\"usersearchtrain\">Search By TrainNo</a></li>\r\n");
      out.write("            <li class=\"nav-item\"><a class=\"nav-link\" href=\"userprofile\">Profile</a></li>\r\n");
      out.write("            <li class=\"nav-item\"><a class=\"nav-link\" href=\"userlogout\">Logout</a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"container my-5\">\r\n");
      out.write("\r\n");
      out.write("      <!-- Input Form Card -->\r\n");
      out.write("      <div class=\"card shadow-sm mb-4\">\r\n");
      out.write("        <div class=\"card-header bg-primary text-white\">\r\n");
      out.write("          <h5 class=\"mb-0\">Fare Enquiry for Trains Between Stations</h5>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"card-body\">\r\n");
      out.write("          <form action=\"fareenq\" method=\"post\" class=\"row g-3\">\r\n");
      out.write("            <div class=\"col-md-6\">\r\n");
      out.write("              <label for=\"fromstation\" class=\"form-label\">From Station</label>\r\n");
      out.write("              <input type=\"text\" class=\"form-control\" id=\"fromstation\" name=\"fromstation\" required>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-6\">\r\n");
      out.write("              <label for=\"tostation\" class=\"form-label\">To Station</label>\r\n");
      out.write("              <input type=\"text\" class=\"form-control\" id=\"tostation\" name=\"tostation\" required>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-12 text-end\">\r\n");
      out.write("              <button type=\"submit\" class=\"btn btn-primary\">Get Fare</button>\r\n");
      out.write("            </div>\r\n");
      out.write("          </form>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      ");
 
         // Pull in whatever the servlet set
         List<TrainBean> trains = (List<TrainBean>) request.getAttribute("trains");
         String fromStation = (String) request.getAttribute("fromStation");
         String toStation   = (String) request.getAttribute("toStation");

         if (trains != null) {
      
      out.write("\r\n");
      out.write("\r\n");
      out.write("      <!-- Results Card -->\r\n");
      out.write("      <div class=\"card shadow-sm\">\r\n");
      out.write("        <div class=\"card-header\">\r\n");
      out.write("          <h5 class=\"mb-0\">Fare Results</h5>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"card-body\">\r\n");
      out.write("          ");
 if (!trains.isEmpty()) { 
      out.write("\r\n");
      out.write("            <p class=\"lead\">\r\n");
      out.write("              Fare for trains between \r\n");
      out.write("              <strong>");
      out.print( fromStation );
      out.write("</strong> and \r\n");
      out.write("              <strong>");
      out.print( toStation );
      out.write("</strong>:\r\n");
      out.write("            </p>\r\n");
      out.write("            <div class=\"table-responsive\">\r\n");
      out.write("              <table class=\"table table-striped table-hover align-middle\">\r\n");
      out.write("                <thead class=\"table-light\">\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <th>Train Name</th>\r\n");
      out.write("                    <th>Train No</th>\r\n");
      out.write("                    <th>From</th>\r\n");
      out.write("                    <th>To</th>\r\n");
      out.write("                    <th>Time</th>\r\n");
      out.write("                    <th>Seats</th>\r\n");
      out.write("                    <th>Fare (₹)</th>\r\n");
      out.write("                    <th>Action</th>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                </thead>\r\n");
      out.write("                <tbody>\r\n");
      out.write("                  ");
 for (TrainBean train : trains) {
                       int hr  = (int)(Math.random()*24);
                       int min = (int)(Math.random()*60);
                       String time = String.format("%02d:%02d", hr, min);
                  
      out.write("\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <td>");
      out.print( train.getTr_name() );
      out.write("</td>\r\n");
      out.write("                    <td>");
      out.print( train.getTr_no()   );
      out.write("</td>\r\n");
      out.write("                    <td>");
      out.print( train.getFrom_stn() );
      out.write("</td>\r\n");
      out.write("                    <td>");
      out.print( train.getTo_stn()   );
      out.write("</td>\r\n");
      out.write("                    <td>");
      out.print( time                );
      out.write("</td>\r\n");
      out.write("                    <td>");
      out.print( train.getSeats()    );
      out.write("</td>\r\n");
      out.write("                    <td>");
      out.print( train.getFare()     );
      out.write("</td>\r\n");
      out.write("                    <td>\r\n");
      out.write("                      <a \r\n");
      out.write("                        class=\"btn btn-sm btn-success\"\r\n");
      out.write("                        href=\"booktrainbyref?trainNo=");
      out.print(train.getTr_no());
      out.write("\r\n");
      out.write("                             &amp;fromStn=");
      out.print(train.getFrom_stn());
      out.write("\r\n");
      out.write("                             &amp;toStn=");
      out.print(train.getTo_stn());
      out.write("\">\r\n");
      out.write("                        Book Now\r\n");
      out.write("                      </a>\r\n");
      out.write("                    </td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  ");
 } 
      out.write("\r\n");
      out.write("                </tbody>\r\n");
      out.write("              </table>\r\n");
      out.write("            </div>\r\n");
      out.write("          ");
 } else { 
      out.write("\r\n");
      out.write("            <div class=\"alert alert-warning\">\r\n");
      out.write("              No trains found between \r\n");
      out.write("              <strong>");
      out.print( fromStation );
      out.write("</strong> and \r\n");
      out.write("              <strong>");
      out.print( toStation   );
      out.write("</strong>.\r\n");
      out.write("            </div>\r\n");
      out.write("          ");
 } 
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Bootstrap JS (Bundle includes Popper) -->\r\n");
      out.write("    <script \r\n");
      out.write("      src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js\"\r\n");
      out.write("      integrity=\"sha384-…\"\r\n");
      out.write("      crossorigin=\"anonymous\">\r\n");
      out.write("    </script>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
