/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.27
 * Generated at: 2025-04-25 18:50:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import com.tms.beans.HistoryBean;

public final class GenerateTicket_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.tms.beans.HistoryBean");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>E-Ticket</title>\r\n");
      out.write("    <!-- Bootstrap CSS -->\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <!-- Bootstrap Icons -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.0/font/bootstrap-icons.css\">\r\n");
      out.write("    <!-- jsPDF for PDF generation -->\r\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js\"></script>\r\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/html2canvas/1.4.1/html2canvas.min.js\"></script>\r\n");
      out.write("    <style>\r\n");
      out.write("        @keyframes fadeInScale {\r\n");
      out.write("            0% { opacity: 0; transform: scale(0.8); }\r\n");
      out.write("            100% { opacity: 1; transform: scale(1); }\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        @keyframes slideIn {\r\n");
      out.write("            0% { transform: translateY(20px); opacity: 0; }\r\n");
      out.write("            100% { transform: translateY(0); opacity: 1; }\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .success-icon {\r\n");
      out.write("            font-size: 5rem;\r\n");
      out.write("            animation: fadeInScale 0.6s cubic-bezier(0.175, 0.885, 0.32, 1.275);\r\n");
      out.write("            background: white;\r\n");
      out.write("            width: 100px;\r\n");
      out.write("            height: 100px;\r\n");
      out.write("            border-radius: 50%;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            margin: 0 auto 20px;\r\n");
      out.write("            box-shadow: 0 4px 20px rgba(0,0,0,0.1);\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .modal-content {\r\n");
      out.write("            border-radius: 15px;\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("            animation: slideIn 0.4s ease-out;\r\n");
      out.write("            box-shadow: 0 10px 30px rgba(0,0,0,0.2);\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .modal-header {\r\n");
      out.write("            background: linear-gradient(135deg, #28a745 0%, #5cb85c 100%);\r\n");
      out.write("            border-bottom: none;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .ticket-container {\r\n");
      out.write("            background: #f8f4e8;\r\n");
      out.write("            border: 1px solid #e0d6c2;\r\n");
      out.write("            border-radius: 8px;\r\n");
      out.write("            max-width: 700px;\r\n");
      out.write("            margin: 30px auto;\r\n");
      out.write("            font-family: 'Segoe UI', sans-serif;\r\n");
      out.write("            display: none;\r\n");
      out.write("            box-shadow: 0 10px 30px rgba(0,0,0,0.1);\r\n");
      out.write("            position: relative;\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .ticket-container::before {\r\n");
      out.write("            content: \"\";\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            top: 0;\r\n");
      out.write("            left: 30px;\r\n");
      out.write("            right: 30px;\r\n");
      out.write("            height: 3px;\r\n");
      out.write("            background: repeating-linear-gradient(to right, #e74c3c 0%, #e74c3c 50%, transparent 50%, transparent 100%);\r\n");
      out.write("            background-size: 20px 3px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .ticket {\r\n");
      out.write("            padding: 25px;\r\n");
      out.write("            position: relative;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .ticket-header {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: space-between;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            margin-bottom: 20px;\r\n");
      out.write("            padding-bottom: 15px;\r\n");
      out.write("            border-bottom: 2px dashed #d1c7b7;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .ticket-title {\r\n");
      out.write("            color: #2c3e50;\r\n");
      out.write("            font-weight: 700;\r\n");
      out.write("            font-size: 1.8rem;\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .ticket-title i {\r\n");
      out.write("            margin-right: 10px;\r\n");
      out.write("            color: #e74c3c;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .ticket-pnr {\r\n");
      out.write("            background: #f1e9d9;\r\n");
      out.write("            padding: 5px 15px;\r\n");
      out.write("            border-radius: 20px;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            color: #2c3e50;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .ticket-table {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            border-collapse: collapse;\r\n");
      out.write("            margin: 20px 0;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .ticket-table th {\r\n");
      out.write("            background: #e8dfce;\r\n");
      out.write("            text-align: left;\r\n");
      out.write("            padding: 12px 15px;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            color: #5d5d5d;\r\n");
      out.write("            width: 30%;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .ticket-table td {\r\n");
      out.write("            padding: 12px 15px;\r\n");
      out.write("            border-bottom: 1px solid #e8dfce;\r\n");
      out.write("            font-weight: 500;\r\n");
      out.write("            color: #333;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .ticket-footer {\r\n");
      out.write("            margin-top: 20px;\r\n");
      out.write("            padding-top: 15px;\r\n");
      out.write("            border-top: 2px dashed #d1c7b7;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .download-btn .btn {\r\n");
      out.write("            background: linear-gradient(135deg, #3498db 0%, #2980b9 100%);\r\n");
      out.write("            border: none;\r\n");
      out.write("            padding: 10px 25px;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            box-shadow: 0 4px 10px rgba(52, 152, 219, 0.3);\r\n");
      out.write("            transition: all 0.3s;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .download-btn .btn:hover {\r\n");
      out.write("            transform: translateY(-2px);\r\n");
      out.write("            box-shadow: 0 6px 15px rgba(52, 152, 219, 0.4);\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .ticket-watermark {\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            right: 20px;\r\n");
      out.write("            bottom: 20px;\r\n");
      out.write("            opacity: 0.1;\r\n");
      out.write("            font-size: 8rem;\r\n");
      out.write("            z-index: 0;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .ticket-valid {\r\n");
      out.write("            background: #f1e9d9;\r\n");
      out.write("            padding: 5px 10px;\r\n");
      out.write("            border-radius: 4px;\r\n");
      out.write("            font-size: 0.9rem;\r\n");
      out.write("            display: inline-block;\r\n");
      out.write("            margin-top: 10px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .ticket-price {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            justify-content: flex-end;\r\n");
      out.write("            margin-top: 10px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .ticket-price i {\r\n");
      out.write("            margin-right: 8px;\r\n");
      out.write("            color: #27ae60;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("          .btn-download {\r\n");
      out.write("            background: linear-gradient(135deg, #3498db 0%, #2980b9 100%);\r\n");
      out.write("            border: none;\r\n");
      out.write("            color: white;\r\n");
      out.write("            box-shadow: 0 4px 10px rgba(52, 152, 219, 0.3);\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .btn-download:hover {\r\n");
      out.write("            transform: translateY(-2px);\r\n");
      out.write("            box-shadow: 0 6px 15px rgba(52, 152, 219, 0.4);\r\n");
      out.write("            color: white;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .btn-home {\r\n");
      out.write("            background: linear-gradient(135deg, #6c757d 0%, #495057 100%);\r\n");
      out.write("            border: none;\r\n");
      out.write("            color: white;\r\n");
      out.write("            box-shadow: 0 4px 10px rgba(108, 117, 125, 0.3);\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .btn-home:hover {\r\n");
      out.write("            transform: translateY(-2px);\r\n");
      out.write("            box-shadow: 0 6px 15px rgba(108, 117, 125, 0.4);\r\n");
      out.write("            color: white;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <!-- Payment Success Modal -->\r\n");
      out.write("    <div class=\"modal fade show\" id=\"paymentModal\" tabindex=\"-1\" aria-labelledby=\"paymentModalLabel\" aria-hidden=\"false\" style=\"display: block; background-color: rgba(0,0,0,0.5);\">\r\n");
      out.write("        <div class=\"modal-dialog modal-dialog-centered\">\r\n");
      out.write("            <div class=\"modal-content\">\r\n");
      out.write("                <div class=\"modal-header text-white\">\r\n");
      out.write("                    <h5 class=\"modal-title\" id=\"paymentModalLabel\"><i class=\"bi bi-credit-card\"></i> Payment Receipt</h5>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"modal-body text-center\">\r\n");
      out.write("                    <div class=\"success-icon\">\r\n");
      out.write("                        <i class=\"bi bi-check-circle-fill text-success\"></i>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <h4 class=\"text-success mb-3\">Payment Successful!</h4>\r\n");
      out.write("                    <p>Your payment of <strong>₹ ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${txn.amount}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</strong> has been processed successfully.</p>\r\n");
      out.write("                    <div class=\"d-flex justify-content-center align-items-center mt-3\">\r\n");
      out.write("                        <i class=\"bi bi-receipt text-primary me-2\" style=\"font-size: 1.2rem;\"></i>\r\n");
      out.write("                        <span>Transaction ID: ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${txn.transId}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"modal-footer justify-content-center\">\r\n");
      out.write("                    <button type=\"button\" class=\"btn btn-primary px-4 py-2\" onclick=\"showTicket()\">\r\n");
      out.write("                        <i class=\"bi bi-ticket-perforated me-2\"></i>View Ticket\r\n");
      out.write("                    </button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Ticket Container (initially hidden) -->\r\n");
      out.write("    <div class='ticket-container' id=\"ticketDisplay\">\r\n");
      out.write("        <div class='ticket' id='ticket-content'>\r\n");
      out.write("            <div class=\"ticket-header\">\r\n");
      out.write("                <h1 class=\"ticket-title\"><i class=\"bi bi-train-front\"></i> E-Ticket</h1>\r\n");
      out.write("                <div class=\"ticket-pnr\">PNR: <span class=\"text-primary\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${txn.transId}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span></div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <table class='ticket-table'>\r\n");
      out.write("                <tbody>\r\n");
      out.write("                    <tr><th>Train Name</th><td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${trainName}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td></tr>\r\n");
      out.write("                    <tr><th>Train No</th><td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${txn.tr_no}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td></tr>\r\n");
      out.write("                    <tr><th>From Station</th><td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${txn.from_stn}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td></tr>\r\n");
      out.write("                    <tr><th>To Station</th><td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${txn.to_stn}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td></tr>\r\n");
      out.write("                    <tr><th>Date of Journey</th><td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${txn.date}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td></tr>\r\n");
      out.write("                    <tr><th>Departure Time</th><td>11:23</td></tr>\r\n");
      out.write("                    <tr><th>Passengers</th><td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${txn.seats}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td></tr>\r\n");
      out.write("                    <tr><th>Class</th><td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${seatClass}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td></tr>\r\n");
      out.write("                </tbody>\r\n");
      out.write("            </table>\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"ticket-price\">\r\n");
      out.write("                <i class=\"bi bi-currency-rupee\"></i>\r\n");
      out.write("                <span style=\"font-size: 1.2rem; font-weight: 600;\">₹ ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${txn.amount}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"ticket-valid\">\r\n");
      out.write("                <i class=\"bi bi-check-circle-fill text-success me-2\"></i>\r\n");
      out.write("                Valid for travel on ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${txn.date}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"ticket-watermark\">\r\n");
      out.write("                <i class=\"bi bi-ticket-perforated\"></i>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("           <div class='ticket-footer'>\r\n");
      out.write("                <button class='btn btn-home btn-ticket' onclick=\"goToHome()\">\r\n");
      out.write("                    <i class=\"bi bi-house-door me-2\"></i>Back to Home\r\n");
      out.write("                </button>\r\n");
      out.write("                <button class='btn btn-download btn-ticket' onclick='downloadPDF()'>\r\n");
      out.write("                    <i class=\"bi bi-download me-2\"></i>Download Ticket\r\n");
      out.write("                </button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Bootstrap JS Bundle with Popper -->\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("    <script>\r\n");
      out.write("    // Initialize jsPDF\r\n");
      out.write("    const { jsPDF } = window.jspdf;\r\n");
      out.write("    \r\n");
      out.write("    function goToHome() {\r\n");
      out.write("        window.location.href = 'UserHome.jsp';\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    // Show ticket and hide modal with animation\r\n");
      out.write("    function showTicket() {\r\n");
      out.write("        const modal = document.getElementById('paymentModal');\r\n");
      out.write("        modal.style.opacity = '0';\r\n");
      out.write("        modal.style.transition = 'opacity 0.3s ease';\r\n");
      out.write("        \r\n");
      out.write("        setTimeout(() => {\r\n");
      out.write("            modal.style.display = 'none';\r\n");
      out.write("            const ticket = document.getElementById('ticketDisplay');\r\n");
      out.write("            ticket.style.display = 'block';\r\n");
      out.write("            ticket.style.animation = 'fadeInScale 0.6s ease-out';\r\n");
      out.write("        }, 300);\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    // Download ticket as PDF\r\n");
      out.write("    function downloadPDF() {\r\n");
      out.write("        const ticketElement = document.getElementById('ticket-content');\r\n");
      out.write("        \r\n");
      out.write("        // Use html2canvas to capture the ticket\r\n");
      out.write("        html2canvas(ticketElement, {\r\n");
      out.write("            scale: 2,\r\n");
      out.write("            logging: false,\r\n");
      out.write("            useCORS: true,\r\n");
      out.write("            allowTaint: true\r\n");
      out.write("        }).then(canvas => {\r\n");
      out.write("            const imgData = canvas.toDataURL('image/png');\r\n");
      out.write("            const pdf = new jsPDF('p', 'mm', 'a4');\r\n");
      out.write("            const imgWidth = 190;\r\n");
      out.write("            const imgHeight = canvas.height * imgWidth / canvas.width;\r\n");
      out.write("            \r\n");
      out.write("            pdf.addImage(imgData, 'PNG', 10, 10, imgWidth, imgHeight);\r\n");
      out.write("            pdf.save(`ticket_");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${'${txn.transId}'}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(".pdf`);\r\n");
      out.write("        });\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    // Close modal when clicking outside\r\n");
      out.write("    window.onclick = function(event) {\r\n");
      out.write("        const modal = document.getElementById('paymentModal');\r\n");
      out.write("        if (event.target === modal) {\r\n");
      out.write("            showTicket();\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
