/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.27
 * Generated at: 2025-04-23 14:02:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.List;
import com.tms.beans.TrainBean;

public final class ViewTrains_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.tms.beans.TrainBean");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"UTF-8\">\r\n");
      out.write("  <title>Admin - View Trains</title>\r\n");
      out.write("  <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("  <script src=\"https://kit.fontawesome.com/a076d05399.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("  <style>\r\n");
      out.write("    .navbar-brand {\r\n");
      out.write("      font-weight: bold;\r\n");
      out.write("      font-size: 1.5rem;\r\n");
      out.write("    }\r\n");
      out.write("    .navbar {\r\n");
      out.write("      background-color: #1d3557;\r\n");
      out.write("    }\r\n");
      out.write("    .nav-link {\r\n");
      out.write("      color: white !important;\r\n");
      out.write("    }\r\n");
      out.write("    .btn1 {\r\n");
      out.write("      padding: 0;\r\n");
      out.write("    }\r\n");
      out.write("    footer {\r\n");
      out.write("      margin-top: 4rem;\r\n");
      out.write("      padding: 3rem 1rem;\r\n");
      out.write("      background-color: #1d3557;\r\n");
      out.write("      color: white;\r\n");
      out.write("      text-align: center;\r\n");
      out.write("    }\r\n");
      out.write("    footer a {\r\n");
      out.write("      color: #ffc107;\r\n");
      out.write("      text-decoration: none;\r\n");
      out.write("    }\r\n");
      out.write("    .footer-container {\r\n");
      out.write("      display: grid;\r\n");
      out.write("      grid-template-columns: repeat(auto-fit, minmax(260px, 1fr));\r\n");
      out.write("      gap: 2rem;\r\n");
      out.write("    }\r\n");
      out.write("    .footer-column h4 {\r\n");
      out.write("      margin-bottom: 1rem;\r\n");
      out.write("      font-size: 1.1rem;\r\n");
      out.write("      color: #ffb703;\r\n");
      out.write("    }\r\n");
      out.write("    .footer-column ul {\r\n");
      out.write("      list-style: none;\r\n");
      out.write("      padding: 0;\r\n");
      out.write("    }\r\n");
      out.write("    .footer-column ul li {\r\n");
      out.write("      margin-bottom: 0.5rem;\r\n");
      out.write("    }\r\n");
      out.write("    .footer-column iframe {\r\n");
      out.write("      width: 100%;\r\n");
      out.write("      height: 160px;\r\n");
      out.write("      border: none;\r\n");
      out.write("      border-radius: 8px;\r\n");
      out.write("    }\r\n");
      out.write("    .footer-column .social-icons a {\r\n");
      out.write("      margin-right: 8px;\r\n");
      out.write("      font-size: 1.2rem;\r\n");
      out.write("      color: #f1faee;\r\n");
      out.write("      transition: color 0.3s;\r\n");
      out.write("    }\r\n");
      out.write("    .footer-column .social-icons a:hover {\r\n");
      out.write("      color: #ffb703;\r\n");
      out.write("    }\r\n");
      out.write("  </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<!-- Navbar -->\r\n");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-dark\">\r\n");
      out.write("  <div class=\"container-fluid\">\r\n");
      out.write("    <a class=\"navbar-brand\" href=\"#\">E-Trains</a>\r\n");
      out.write("    <div class=\"collapse navbar-collapse\">\r\n");
      out.write("      <ul class=\"navbar-nav ms-auto\">\r\n");
      out.write("        <li class=\"nav-item\"><a class=\"nav-link\" href=\"AdminHome.html\">Home</a></li>\r\n");
      out.write("        <li class=\"nav-item\"><a class=\"nav-link\" href=\"adminviewtrainfwd\">View Trains</a></li>\r\n");
      out.write("        <li class=\"nav-item\"><a class=\"nav-link\" href=\"adminsearchtrainfwd\">Search By TrainNo</a></li>\r\n");
      out.write("        <li class=\"nav-item\"><a class=\"nav-link\" href=\"addtrainfwd\">Add Train</a></li>\r\n");
      out.write("        <li class=\"nav-item\"><a class=\"nav-link\" href=\"cancletrainfwd\">Delete Train</a></li>\r\n");
      out.write("        <li class=\"nav-item\"><a class=\"nav-link\" href=\"updatetrain\">Update Train</a></li>\r\n");
      out.write("        <li class=\"btn btn-sm btn-danger btn1\"><a class=\"nav-link\" href=\"adminlogout\">Logout</a></li>\r\n");
      out.write("      </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container mt-5\">\r\n");
      out.write("  <h3 class=\"text-center mb-4\">Running Trains</h3>\r\n");
      out.write("  ");

    List<TrainBean> trains = (List<TrainBean>) request.getAttribute("trains");
    if (trains != null && !trains.isEmpty()) {
  
      out.write("\r\n");
      out.write("  <div class=\"table-responsive\">\r\n");
      out.write("    <table class=\"table table-striped table-hover table-bordered\">\r\n");
      out.write("      <thead class=\"table-dark\">\r\n");
      out.write("        <tr>\r\n");
      out.write("          <th>Train Name</th>\r\n");
      out.write("          <th>Train Number</th>\r\n");
      out.write("          <th>From Station</th>\r\n");
      out.write("          <th>To Station</th>\r\n");
      out.write("          <th>Seats Available</th>\r\n");
      out.write("          <th>Fare (INR)</th>\r\n");
      out.write("          <th>Action</th>\r\n");
      out.write("        </tr>\r\n");
      out.write("      </thead>\r\n");
      out.write("      <tbody>\r\n");
      out.write("        ");
 for (TrainBean train : trains) { 
      out.write("\r\n");
      out.write("        <tr>\r\n");
      out.write("          <td><a href=\"viewadmin?trainNo=");
      out.print( train.getTr_no() );
      out.write("&fromStn=");
      out.print( train.getFrom_stn() );
      out.write("&toStn=");
      out.print( train.getTo_stn() );
      out.write('"');
      out.write('>');
      out.print( train.getTr_name() );
      out.write("</a></td>\r\n");
      out.write("          <td>");
      out.print( train.getTr_no() );
      out.write("</td>\r\n");
      out.write("          <td>");
      out.print( train.getFrom_stn() );
      out.write("</td>\r\n");
      out.write("          <td>");
      out.print( train.getTo_stn() );
      out.write("</td>\r\n");
      out.write("          <td>");
      out.print( train.getSeats() );
      out.write("</td>\r\n");
      out.write("          <td>");
      out.print( train.getFare() );
      out.write(" RS</td>\r\n");
      out.write("          <td><a href=\"adminupdatetrain?trainnumber=");
      out.print( train.getTr_no() );
      out.write("\">Update</a></td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("      </tbody>\r\n");
      out.write("    </table>\r\n");
      out.write("  </div>\r\n");
      out.write("  ");
 } else { 
      out.write("\r\n");
      out.write("    <div class=\"alert alert-warning text-center\">No Running Trains Found</div>\r\n");
      out.write("  ");
 } 
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- Footer -->\r\n");
      out.write("<footer>\r\n");
      out.write("  <div class=\"container footer-container\">\r\n");
      out.write("    <div class=\"footer-column\">\r\n");
      out.write("      <h4>Follow Us</h4>\r\n");
      out.write("      <div class=\"social-icons\">\r\n");
      out.write("        <a href=\"#\"><i class=\"fab fa-facebook\"></i></a>\r\n");
      out.write("        <a href=\"#\"><i class=\"fab fa-twitter\"></i></a>\r\n");
      out.write("        <a href=\"#\"><i class=\"fab fa-instagram\"></i></a>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"footer-column\">\r\n");
      out.write("      <h4>Location</h4>\r\n");
      out.write("      <ul>\r\n");
      out.write("        <li>11218 John Galt Blvd Ste 301</li>\r\n");
      out.write("        <li>Mumbai, Maharashtra</li>\r\n");
      out.write("        <li>Pincode - 400053</li>\r\n");
      out.write("      </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"footer-column\">\r\n");
      out.write("      <h4>Our Location</h4>\r\n");
      out.write("      <iframe src=\"https://www.google.com/maps/embed?pb=!1m18...\"></iframe>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</footer>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
